### ISSUE TITLE
Milestone #1 Feedback

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/explorePy#13]
Great job team! Your packages are well set up and look ready to flourish. On the whole your documentation and organization was excellent. A few specific comments on your work:

Proposal:
- This is a very small comment but I would recommend making the section headers on your readme a bit larger. It would make the readme easier to navigate/understand.

Functions:
- Your functions do not have a dummy output. No worries, I don't think it explicitly said that on the Milestone 1 page, but it would have been nice to have.
- When you actually write the functions, make sure to include appropriate comments (include inputs and outputs).

Tests:
- Your test descriptions are good, but it might be useful if you included specific error messages with each of your tests.
- Why did you comment out loading the `testthat` library?
- You should test other inputs, e.g. list, array, vector, tibble.

**Comment by rachelkriggs** [comment]
- section headers on readme made larger
- comments added to all functions
- error messages added to tests
- `testthat` will be addressed in Milestone3 with R package
- input tests whether or not a dataframe is passed in, will accept inputs that are not dataframes and output an error message stating 'Input is not a pandas data frame'
