### ISSUE TITLE
Updating Python Tests

### ISSUE THREAD

**Issue by nazra-inari** [UBC-MDS/explorePy#28]
I am updating the python test files to import the package functions and run the tests on the functions instead of dummy input.

Furthermore, I am also running the pytests in terminal to ensure that they all pass. I will provide the procedure for each of you to run the test locally as on your as well.

**Comment by jpush1773** [comment]
I ran the tests from the local test folder after merging Arzan's changes and pytest ran without error. See screenshot. Within the screenshoot, you can follow the process of navigating to test folder and then running `pytest`.
![image](https://user-images.githubusercontent.com/43223067/53582771-fff38b80-3b34-11e9-86ac-27acad01ff1c.png)
