### ISSUE TITLE
Feedback on Milestone #2

### ISSUE THREAD

**Issue by rainerlempert** [UBC-MDS/explorePy#30]
Good job building and organizing your repo! Your documentation was good and your functions are sound. A few specific comments on your testing protocol and workflow management:
- Your tests fail when I run them using `pytest`. The error is always the same: "fixture 'x' not found". I think this is because you are placing an undefined variable, `x`, inside each of the test function calls. You also did not actually test the functions you wrote. I'm sorry if there was a gap in communication regarding how your tests should be developed. 
As we discussed in lab yesterday, I believe you should do something like this to import your functions:
`import sys` 
`sys.path.append("../explorePy")` 
`import missing_values` 
After doing this, you can can call the functions in your package inside the test functions. There is (usually) no need to place arguments like `x` inside the test function calls. If you have further questions about this I would recommend you talk to Varada, she is a Python whiz and I am unfortunately a Python novice.
- In the future, it would be great if you could raise issues to help manage workflow.
- I noticed that only @rachelkriggs  and @nazra-inari contributed to this repo. Are the other team members planning to build the R repo?

Sorry about the late feedback, and please don't hesitate to reach out to me or any of the other TAs if you have any questions.

**Comment by rachelkriggs** [comment]
Hi Rainer, just a quick note to address your last bullet point.  I noticed that when you visit the Contributors page (https://github.com/UBC-MDS/explorePy/graphs/contributors) you are correct in that you only see my name and Arzan's. I'm not sure why this is. If you go to the commits (https://github.com/UBC-MDS/explorePy/commits/master) you will see a more accurate representation of who contributed. I don't know why this shows as it does on the Contributors page as it seems incorrect.

**Comment by rachelkriggs** [comment]
Also, just want to ask a question regarding the second to last bullet point:
We did raise issues for Milestone 2, and then closed them as we completed the work. Could you specify what more we should be doing? Thanks!

**Comment by rainerlempert** [comment]
Hi @rachelkriggs thanks for the clarifications on those last two points! I guess for the future it would be helpful for my purposes if you could leave the issues open until I submit feedback on the milestone/project. Sorry if that makes things a bit annoying on your end!

**Comment by rachelkriggs** [comment]
@rainerlempert Noted. We may have already closed some issues for Milestone 3 but moving forward this week we will leave them open.
